FROM python:3.6-alpine

WORKDIR /app

VOLUME /outdir

COPY . .

RUN apk update && apk upgrade && apk add ca-certificates wget && pip install -r requirements.txt

ENTRYPOINT ["/bin/ash", "./entrypoint.sh"]
